apiVersion: skaffold/v2beta18
kind: Config
profiles:
  - name: dev
    build:
      local:
        push: false # true: 서버 테스트 / false: 로컬 테스트
      artifacts:
        # - image: feet312/simple-api # on dev server
        - image: microserviceone   # local
          jib:
            args:
              - -DskipTests
#              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=dev"
            fromImage: openjdk:11.0.11-jre-slim
    deploy:
      kubectl:
        manifests:
         
          - k8s/dev/apidoc-*.yaml 
portForward:
   - resourceType: Service
     resourceName: microserviceone-service
     namespace: apidoc-aggregator
     port: 8080
     localPort: 8081 # *Optional*