apiVersion: v1
kind: configMap
metadata:
  name: commonui-configmap 
  namespace: apidoc-aggregator
  
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: apidoc-aggregator
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-reader-binding
  namespace: apidoc-aggregator
subjects:
- kind: ServiceAccount
  name: default
#  name: dev
  apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""