apiVersion: apps/v1
kind: Deployment
metadata:
  name: microserviceone-deploy
  namespace: apidoc-aggregator
  labels:
    app: microserviceone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microserviceone
  template:
    metadata:
      labels:
        app: microserviceone
    spec:
      containers:
      - name: microserviceone
        image: microserviceone  # on server
        # image: microserviceone
        ports: 
        - name: http
          containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: microserviceone-service
  namespace: apidoc-aggregator
spec:
  # type: NodePort
  selector:
    app: microserviceone
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
      # nodePort: 32180
---
