apiVersion: apps/v1
kind: Deployment
metadata:
  name: commonui-deploy
  namespace: apidoc-aggregator
  labels:
    app: commonui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: commonui
  template:
    metadata:
      labels:
        app: commonui
    spec:
      containers:
      - name: commonui
        image: commonui  # on server
        # image: commonui
        ports: 
        - name: http
          containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: commonui-service
  namespace: apidoc-aggregator
spec:
  # type: NodePort
  selector:
    app: commonui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
      # nodePort: 32180
---
