apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicetwo-deploy
  namespace: apidoc-aggregator
  labels:
    app: microservicetwo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservicetwo
  template:
    metadata:
      labels:
        app: microservicetwo
    spec:
      containers:
      - name: microservicetwo
        image: microservicetwo  # on server
        # image: microserviceone
        ports: 
        - name: http
          containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: microservicetwo-service
  namespace: apidoc-aggregator
spec:
  # type: NodePort
  selector:
    app: microservicetwo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
      # nodePort: 32180
---
